<<<<<<< HEAD
version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
=======
version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
>>>>>>> 187da7a (Github actions.)
      sh -c "python manage.py runserver 0.0.0.0:8000"